### ISSUE TITLE
Logrotate issue when OS uses the upstart init system

### ISSUE THREAD

**Issue by mattock** [voxpupuli/puppet-etherpad#22]
This module can add an upstart init script to /etc/init/etherpad.conf. Now that PR https://github.com/voxpupuli/puppet-etherpad/pull/14 is merged, the upstart init script also works as intended.

That said, one problem remains, and that affects at least Ubuntu 14.04. Upstart has a generic log rotation config in _/etc/logrotate.d/upstart_ for all upstart-managed services:
```
/var/log/upstart/*.log {
        daily
        missingok
        rotate 7
        compress
        notifempty
        nocreate
}
```
Upstart write output from etherpad to _/var/log/upstart/etherpad.log_, and attempts to rotate the logfile using the above generic rules. The generic rule works fine for all other services, but when logrotate rotates etherpad.log, it outputs a warning:
```
/etc/cron.daily/logrotate:
gzip: stdin: file size changed while zipping
```
This is problematic when the server is configured to forward root email to a real email address.

Apparently the "delaycompress" option in the upstart logrotate config would fix this. However, messing with a generic upstart logrotate configuration file seems rather invasive. The problem is made worse by the fact that logrotate's config override mechanism does not allow overriding log paths. I tested this by adding _/etc/logrotate.d/etherpad.conf_ like this:
```
/var/log/upstart/etherpad.log
{
        rotate 4
        daily 
        missingok
        notifempty
        compress
        delaycompress
        sharedscripts
        postrotate
                restart etherpad >/dev/null 2>&1 || true
        endscript
}
```
When this file was in place, logrotate would fail hard with
```
/etc/cron.daily/logrotate:
error: upstart:1 duplicate log entry for /var/log/upstart/etherpad.log
```
Does anyone know of a way to make etherpad itself work more smoothly with log rotation? That seems like the only option to fix this without messing directly with upstart's generic logrotate config and possibly breaking log rotation elsewhere.

**Comment by Dan33l** [comment]
For the moment only Ubuntu 16.04 is supported by this module. And this version of OS does not use upstart init.

Ubuntu 14.04 is EOL in febuary. If you really need this OS feel free to propose a PR. But support in module will be removed when OS will be EOL.

**Comment by Dan33l** [comment]
Ubuntu 14.04 is now EOL and not indicated as accepted OS in `metadata.json`.
