### ISSUE TITLE
Use variables instead of hard coded text in template settings.json.epp

### ISSUE THREAD

**Issue by your1p** [voxpupuli/puppet-etherpad#44]
## Affected Puppet, Ruby, OS and module versions/distributions

- Distribution: All supported nodesets
- Module version: 2.0.0

## What are you seeing

The template contains unvaried options.

## What behaviour did you expect instead

To be able to modifying all etherpad options in the template and use functions like  to_json_pretty to improve this module.

**Comment by your1p** [comment]
In the issue #38, alexfisher says that it could be interesting to use ``to_json_pretty`` (https://github.com/voxpupuli/puppet-etherpad/pull/39#pullrequestreview-119483742)
So, I used ``to_json_pretty`` for ``settings.json.epp`` but for complex elements, the syntax it's not good. It's output a hash in my ``settings.json`` file.

**Comment by your1p** [comment]
This is an exemple `ip` and `port` are simple elements, `padoptions` and `ssl` are complex elements.
```
 $myhash = {
              'ip'         => "0.0.0.0",
              'port'       => "9001",
              'padOptions' => {
                                'nocolors' => 'false',
                                'showcontrols'     => 'true',
                                'showchat'         => 'true',
                                'showlinenumbers'  => 'true',
                                'usemonospacefont' => 'false',
                                'username'         => 'false',
                                'usercolor'        => 'false',
                                'rtl'              => 'false',
                                'alwaysshowchat'   => 'false',
                                'chatandusers'     => 'false',
                                'lang'             => 'en-gb',
                               }
              'ssl'        => {
                                'key'  => '/etc/ssl/epad/epl-server.key',
                                'cert' => '/etc/ssl/epad/epl-server.crt',
                              }
  }
  ```
  
Below this is the output of the upper peace of puppet code. We can say that `to_json_pretty` don't generate a good JSON syntax. 
  ```
  "ssl": "{key : /etc/ssl/epad/epl-server.key, cert : /etc/ssl/epad/epl-server.key}"
  "ip": "{ip => 127.0.0.1}",
  "port": "{port => 9001}",
  "port": "{ip => 9001}",
  "padOptions": "{nocolors => false, showcontrols => true, showchat => true, showlinenumbers => true, usemonospacefont => false, username => false, usercolor => false, rtl => false, alwaysshowchat => false, chatandusers => false, lang => en-gb}",

```

**Comment by your1p** [comment]
I used this JSON Validator https://codebeautify.org/jsonvalidator ans he says that the settings.json file generated by `stdlib/to_json_pretty` is a Valid JSON but Etherpad can't read this file.

**Comment by bastelfreak** [comment]
which errors do you get? is that something that we can fix by changing the puppet hash?

**Comment by your1p** [comment]
When I put the peace of code in a JSON validator, it say that the code is OK but when I use this code in etherpad, I have several syntax errors. I think changing the puppet hash will don't fix errors.

**Comment by alexjfisher** [comment]
@your1p Does the case of keys in `padOptions` not also matter?

**Comment by your1p** [comment]
After creating a fork to put to_pretty_json on setting.json.epp, I could see the application limits of this resource. So I opted for the merge resource. I think it's easier to implemented on your code. You can see my PR #44. Waiting for your answer @alexjfisher and @bastelfreak.
